apiVersion: v1
kind: Pod
metadata:
  name: test-hello-world-debug
  labels:
    app: test-hello-world
spec:
  containers:
  - name: test-hello-world-debug
    image: ghcr.io/izumanetworks/test-hello-world-debug:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 8090
    env:
    - name: HELLO_NAME
      value: "Debug"
    - name: HELLO_PORT
      value: "8090"
  imagePullSecrets:
    - name: regcred
