apiVersion: v1
kind: Pod
metadata:
  name: test-hello-world
  labels:
    app: test-hello-world
spec:
  containers:
  - name: test-hello-world
    image: ghcr.io/izumanetworks/test-hello-world:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 8080
    env:
    - name: HELLO_NAME
      value: "Kubernetes"
    livenessProbe:
      httpGet:
        path: /hello
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
  imagePullSecrets:
    - name: regcred
